<h1 class="page-header">Заявки на вступление в кооператив</h1>

<?php if (count($this->records)): ?>
<table class="table table-striped">
    <caption></caption>
    <thead>
        <tr>
            <th>Дата</th>
            <th>Организация</th>
            <th>ФИО</th>
            <th>Телефон</th>                
            <th>Email</th>
            <th>Описание</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->records as $r): ?>

    <tr>
        <td>
            <?php echo $r['date_doc']; ?>
        </td>
        <td>
            <?php echo $r['fullname']; ?>
        </td>
        <td>
            <?php echo trim(trim($r['family']. ' ' . $r['name']) . ' ' . $r['name2']); ?>
        </td>
        <td>
            <?php echo $r['phone']; ?>
        </td>
        <td>            
            <a href="mailto:<?php echo $r['email']; ?>"><?php echo $r['email']; ?></a>
        </td>
        <td>
            <?php echo $r['note']; ?>
        </td>
    </tr>

    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="alert alert-info">
    <strong>Нет заявок</strong>
</div>
<?php endif; ?>

