<div class="col-sm-12">
    <h2>Корзина</h2>
    <?php if (count($this->records)): ?>
    <form role="form" method="POST" action="<?php echo $this->url(array(), 'basket'); ?>">
        <table class="table table-bordered">
            <col width="10%">
            <col width="50%">
            <col width="10%">
            <col width="10%">
            <col width="10%">
            <col width="10%">
            <caption></caption>
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Товар</th>
                    <th>Количество</th>
                    <th>Цена</th>
                    <th>Сумма</th>
                    <th>Удалить</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->records as $r): ?>

            <tr>        
                <td>
                    <?php echo $r['good']; ?>
                </td>
                <td>
                    <?php echo $r['name']; ?>
                </td>
                <td>
                    <input type="number" name="count[<?php echo $r['id']; ?>]" class="form-control" value="<?php echo $r['count']; ?>">
                </td>
                <td>
                    <?php echo $r['price']; ?> &#8381;
                </td>
                <td>
                    <?php echo money_format('%i', $r['count'] * $r['price']); ?> &#8381;
                </td>
                <td>
                    <div class="text-center">
                        <input type="checkbox" name="remove[]" value="<?php echo $r['id'];?>" />
                    </div>
                </td>
            </tr>

            <?php endforeach; ?>
            <tr>
                <td colspan="4"><div class="text-right"><b>Итого</b></div></td>
                <td>
                    <b><?php echo $this->summa; ?> &#8381;</b>
                </td>
                <td></td>
            </tr>
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-refresh"></span>
            Пересчитать
        </button>
        <a href="<?php echo $this->url(array(), 'basket-send'); ?>" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span>
            Отправить
        </a>
    </form>
    <?php else: ?>
    <div class="alert alert-info">
        <strong>Ваша корзина пуста</strong>
    </div>
    <?php endif; ?>
</div>