<h2>Оплата членских целевых взносов</h2> 

<div class="thumbnail">
    <div class="caption">
        <h3>
            Пайщики Потребительского Кооператива «Содействие» всегда могут оплатить 
            членские целевые взносы не выходя из дома
        </h3>
        <p>Для того чтобы оплатить членские целевые взносы online Вы можете:</p>
        <p>- Воспользоваться картой <a href="http://www.sdm.ru/" target="_blank">«СДМ-Банк» (ПАО)</a>, и выполнить оплату через <a href="https://retail.sdm.ru/" target="_blank">Интернет Банк</a></p>
        <p>- Воспользоваться формой оплаты на этой странице (комиссия - 3%, но не меньше 30 руб.)</p>
    </div> 
</div>

<iframe
    class="iframe"
    src="https://money.yandex.ru/fastpay/form/02662f6f395d419ab701104992a1afee" 
    style="width: 100%; height: 500px; margin-bottom: 30px; border: 1px solid #e8e8e8;">        
</iframe>