<div>
    <address>
        <strong>Контактная информация:</strong><br>
        Телефон: +7 (831) 216-27-12<br>
        Email: <a href="mailto:info@zolushka52.ru?subject=Письмо с сайта">info@zolushka52.ru</a><br>
        Адрес: г. Нижний Новгород, ул. Советская д. 20, помещение П9, офис 6
    </address>
</div>

<a class="dg-widget-link" href="http://2gis.ru/n_novgorod/firm/70000001022682075/center/43.951578140258796,56.32370016131535/zoom/16?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=bigMap">
    Посмотреть на карте Нижнего Новгорода
</a>
<div class="dg-widget-link">
    <a href="http://2gis.ru/n_novgorod/center/43.951572,56.3237/zoom/16/routeTab/rsType/bus/to/43.951572,56.3237╎НН-хостел?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=route">
        Найти проезд до НН-хостел
    </a>
</div>
<script charset="utf-8" src="http://widgets.2gis.com/js/DGWidgetLoader.js"></script>
<script charset="utf-8">
    new DGWidgetLoader({
        "width":"100%",
        "height":"500",
        "borderColor":"#a3a3a3","pos":{"lat":56.32370016131535,"lon":43.951578140258796,"zoom":16},
        "opt":{"city":"n_novgorod"},"org":[{"id":"70000001022682075"}]});
</script>
<noscript style="color:#c00;font-size:16px;font-weight:bold;">
    Виджет карты использует JavaScript. Включите его в настройках вашего браузера.
</noscript>

