<div>
    <address>
        <strong>Контактная информация:</strong><br>
        Телефон: +7 (831) 216-27-12, +7 (831) 4-11-11-40<br>
        Email: <a href="mailto:vygodno.vmeste@yandex.ru?subject=Письмо с сайта">vygodno.vmeste@yandex.ru</a><br>
        Почтовый адрес: г. Нижний Новгород, ул. Советская д. 20, помещение П9, офис 6<br>
        Пункт выдачи покупок: г. Нижний Новгород, ул. Бекетова, 3А, к33, территория Овощной базы №4<br>
        Проезд любым транспортом до ост. "Музыкальное училище", "Дворец Спорта"
    </address>
</div>

<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
    ymaps.ready(init);
    var myMap, 
        myPlacemark;

    function init(){ 
        myMap = new ymaps.Map("map", {
            center: [56.28972796, 43.98710038],
            zoom: 17
        }, {
            searchControlProvider: 'yandex#search'
        }); 

        myPlacemark = new ymaps.Placemark([56.28972796, 43.98710038], {
            hintContent: 'ПК ВО Содействие', 
            balloonContent: 'Мы тут!' 
        });

        myMap.geoObjects.add(myPlacemark);
    }
</script>

<div id="map" style="width: 100%; height: 500px; margin-bottom: 30px"></div>

<noscript style="color:#c00;font-size:16px;font-weight:bold;">
    Виджет карты использует JavaScript. Включите его в настройках вашего браузера.
</noscript>

