<div>
    <address>
        <strong>Контактная информация:</strong><br>
        Телефон: (831) 216-27-12, 411-11-40<br>
        Email: <a href="mailto:info@zolushka52.ru?subject=Письмо с сайта" target="_blank">info@zolushka52.ru</a><br>
        Адрес: 603057, Нижний Новгород, ул. Бекетова, 3А, к33, территория Овощной базы №4<br>
        Проезд любым транспортом до ост. "Музыкальное училище", "Дворец Спорта"
    </address>
</div>
<script charset="utf-8" type="text/javascript" src="http://firmsonmap.api.2gis.ru/js/DGWidgetLoader.js"></script>
<script charset="utf-8" type="text/javascript">
    new DGWidgetLoader({
        "borderColor":"#a3a3a3",
        "width":"100%",
        "height":"500",
        "wid":"f924d49533413b6f6bab4a5ae4a3d42e",
        "pos":{"lon":"43.986053933549","lat":"56.28924495776","zoom":"17"},
        "opt":{"ref":"hidden","card":["name","schedule"],"city":"n_novgorod"},
        "org":[{"id":"2674541560336718"}]
    });
</script>
<noscript style="color:#c00;font-size:16px;font-weight:bold;">
    Виджет карты использует JavaScript. Включите его в настройках вашего браузера.
</noscript>

