<div class="col-sm-9">
    <h4>ПОТРЕБИТЕЛЬСКИЙ КООПЕРАТИВ ВЗАИМНОГО ОБЕСПЕЧЕНИЯ «СОДЕЙСТВИЕ»</h4>
    <p>Далее приведены основные реквизиты кооператива</p>
    <dl class="dl-horizontal">
        <dt>ИНН</dt>
        <dd>5257168653</dd>

        <dt>КПП</dt>
        <dd>525701001</dd>

        <dt>Юр. адрес</dt>
        <dd>603002 г. Нижний Новгород, ул.Советская , д.20, пом. П9,офис 6</dd>

        <dt>р/с</dt>
        <dd>40703810607000000017</dd>

        <dt>к/с</dt>
        <dd>30101810800000000745</dd>

        <dt>Банк</dt>
        <dd>ФИЛИАЛ «СДМ-Банк» (ПАО) в г.Нижний Новгород</dd>

        <dt>БИК</dt>
        <dd>042202745</dd>
    </dl>

    <h4>Потребительский кооператив взаимного обеспечения «СОДЕЙСТВИЕ» является клиентом «СДМ-Банк» (ПАО)</h4>
    <p>«СДМ-Банк» (ПАО) основан 9 декабря 1991 года (Генеральная лицензия Банка России № 1637), 
        с октября 2004 года входит в Систему обязательного страхования вкладов (свидетельство № 69).</p>
    <p>Банк занимает устойчивые рыночные позиции, имеет стабильные финансовые показатели. 
        В состав акционеров СДМ-Банка входит Европейский Банк Реконструкции и Развития (ЕБРР).</p>
    <p>Предлагаем ознакомится с преимущемтвами владения банковской картой «СДМ-Банк»</p>
    <div class="livelist">
        <ol>
            <li>Минимальная цена владения</li>
            <li>Возможность оплаты во всех магазинах и организациях</li>
            <li>Начисление процентов на остаток денежных средств на карте (с тарифами подробнее можно ознакомиться <a href="http://www.sdm.ru/personal/cards/" target="_blank">тут</a>)</li>
            <li>Отсутствие необходимости лично приезжать в кооператив для оплаты членских, паевых и других взносов, что экономит примерно 50 руб. в месяц на транспорт</li>        
            <li>Нет нужды стоять в пробкахи терять время. Экономия на бензине примерно 90 руб.</li>
            <li>Нет комиссии банка на внутренние переводы. Экономия от 1% до 3% от суммы, но не менее 30 руб.</li>
            <li>Возможность пополнить карту на <a href="http://www.sdm.ru/koordinaty/" target="_blank">150 терминалах "Платформа"</a></li>
            <li>Окупаемость карты при участии в программе "Стол заказов" и "Выгодное топливо" достигается в первый месяц владения</li>
            <li><a href="http://www.sdm.ru/koordinaty/2310/" target="_blank">Оформление карты</a> всего 15 минут</li>
        </ol>

    </div>
</div>

<div class="col-sm-3 hidden-xs hidden-sm">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="/img/carousel/slide1.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>к сотрудничеству производителей и поставщиков товаров народного потребления</p>                            
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/slide2.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>к сотрудничеству менеджеров отделов снабжения предприятий</p>                            
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/slide3.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>к сотрудничеству менеджеров активных продаж</p>                            
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/slide4.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>предпринимателей к совместной закупке</p>                            
          </div>
        </div>
      </div>
    </div>
</div>
