<div class="row">

    <div class="col-sm-8 blog-main">

        <h2>Цели и задачи потребительского кооператива «Содействие»</h2>
        <p>Главной целью ПК ВО «Содействие» является повышение благосостояния, качества и уровня жизни
        членов кооператива и их семей путем объединения усилий и ресурсов.
        Потребительский кооператив позволяет эффективно решать проблемы, стоящие перед его членами,
        в первую очередь, связанные с обеспечением их товарами и услугами высокого качества,
        минимизируя затраты и риски на их решение.</p>

        <p>Для решения этих задач ПК ВО «Содействие» открывает для своих членов следующие программы:</p>
        <?php if (count($this->resources)): ?>
        <ol>
            <?php foreach ($this->resources as $r): ?>
            <li>
                <dt>
                    <a href="<?php echo $this->url(array('id' => $r['id']), 'resources'); ?>">
                        Целевая программа "<?php echo $r['name']; ?>"
                    </a>
                </dt>
                <dd>
                    <?php echo $r['note']; ?>
                </dd>
            </li>
            <?php endforeach; ?>
        </ol>
        <?php else: ?>
        <div class="alert alert-info">
            <strong>В системе не зарегестрировано программ</strong>
        </div>
        <?php endif; ?>

        <p>Хотите улучшить качество своей жизни и жизни Ваших детей?<br>
        Приходите к нам, и мы вместе сделаем нашу жизнь лучше и достойнее!</p>
        <br>
        
        <h4>Регистрационные документы Потребительского Кооператива</h4>
        <div class="row placeholders">
            <div class="col-xs-6 col-sm-2 placeholder">
              <a href="img/reg-1.jpg" target="blank">
                  <img src="img/reg-1.jpg" class="img-thumbnail" width="58" height="84">
              </a>
            </div>

            <div class="col-xs-6 col-sm-2 placeholder">
              <a href="img/reg-2.jpg" target="blank">
                  <img src="img/reg-2.jpg" class="img-thumbnail" width="58" height="84">
              </a>
            </div>
        </div>
        <h4>Прочие документы</h4>
        <div class="row placeholders">
            <div class="col-xs-6 col-sm-4 placeholder">
              <a href="/files/StolZakazov.pdf" target="blank">
                  <img src="/img/docico.png" class="img-thumbnail" width="58" height="84">
                  <div>Положение ЦП "Стол заказов"</div>
              </a>
            </div>
        </div>
        <br>
    </div>

    <div class="col-sm-4 blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <?php echo $this->form; ?>
      </div>
    </div><!-- register -->
</div>
