<div class="col-sm-9">
    <h2>Цели и задачи Потребительского Кооператива «Содействие»</h2>
    <p>Главной целью ПК ВО «Содействие» является повышение благосостояния, качества и уровня жизни
    членов кооператива и их семей путем объединения усилий и ресурсов.
    Потребительский кооператив позволяет эффективно решать проблемы, стоящие перед его членами,
    в первую очередь, связанные с обеспечением их товарами и услугами высокого качества,
    минимизируя затраты и риски на их решение.</p>

    <p>Для решения этих задач ПК ВО «Содействие» открывает для своих членов следующие программы:</p>
    <?php if (count($this->resources)): ?>
    <ul class="media-list">
        <?php 
            foreach ($this->resources as $r): 
                $link = $this->url(array('page' => $r['page']), 'program');                
            ?>
        <li class="media">
            <a class="pull-left" href="<?php echo $link ?>">
                <img class="media-object" src="/img/link.png" alt="К страничке целевой программы" width="64" height="64">
            </a>
            <div class="media-body ">
                <h4><a href="<?php echo $link ?>">Целевая программа "<?php echo $r['name']; ?>"</a></h4>
                <?php echo $r['note']; ?>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php else: ?>
    <div class="alert alert-info">
        <strong>В системе не зарегестрировано программ</strong>
    </div>
    <?php endif; ?>

    <p>Хотите улучшить качество своей жизни и жизни Ваших детей?<br>
    Приходите к нам, и мы вместе сделаем нашу жизнь лучше и достойнее!</p>
    <br>

    <h4>Регистрационные документы Потребительского Кооператива</h4>
    <div class="row placeholders">
        <div class="col-xs-6 col-sm-2 placeholder">
          <a href="img/reg-1.jpg" target="blank" data-lightbox="roadtrip" data-title="Свидетельство о постановке на учет">
              <img src="img/reg-1.jpg" class="img-thumbnail" width="58" height="84">
          </a>
        </div>

        <div class="col-xs-6 col-sm-2 placeholder">
          <a href="img/reg-2.jpg" target="blank" data-lightbox="roadtrip" data-title="Свидетельство о регистрации">
              <img src="img/reg-2.jpg" class="img-thumbnail" width="58" height="84">
          </a>
        </div>
    </div>
    <br>
</div>

<div class="col-sm-3 hidden-xs hidden-sm">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="/img/carousel/slide1.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>к сотрудничеству производителей и поставщиков товаров народного потребления</p>                            
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/slide2.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>к сотрудничеству менеджеров отделов снабжения предприятий</p>                            
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/slide3.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>к сотрудничеству менеджеров активных продаж</p>                            
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/slide4.png">
          <div class="carousel-caption">
              <h3>Приглашаем</h3>
              <p>предпринимателей к совместной закупке</p>                            
          </div>
        </div>
      </div>
    </div>
    <br>
    
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?152"></script>

    <!-- VK Widget -->
    <div id="vk_groups"></div>
    <script type="text/javascript">
    VK.Widgets.Group("vk_groups", {mode: 3}, 143698905);
    </script>
</div>
