<div class="row">

    <div class="col-sm-8 blog-main">      
      <h2>Наши партнеры</h2>
      <p>Участникам кооператива нашими партнерами предоставлены скидки</p>
      <table>
          <tr>
              <td style="vertical-align: top">
                  <br>
                  <a href="http://zolushka52.ru/">
                      <img width="180" src="http://zolushka52.ru/img/zolushka.png">
                  </a>
              </td>
              <td style="padding-left: 10px">
                  <br>
                  <p>
                      ООО "Спец-Ресурс" - оптово-розничная компания по продаже 
                      бытовой химии, косметики, парфюмерии, хозтоваров и канцтоваров. 
                      Оптово-розничный склад компании в Нижнем Новгороде 
                      называется "Торговый дом Золушка".
                  </p>
                  <span class="label label-info">Скидка составляет <?php echo $this->discounts['zolushka']; ?>%</span>
              </td>
          </tr>
          <tr>
              <td style="vertical-align: top">
                  <br>
                  <a href="http://www.hoztovary.nnov.ru/">
                      <img width="180" src="http://www.hoztovary.nnov.ru/img/logo.png">
                  </a>                  
              </td>
              <td style="padding-left: 10px">
                  <br>
                  <p>
                      Розничная торговля - хозтовары, мебель "НОХТ" 58 лет на рынке
                      хозтоваров. Ассортимент 50тысяч наименований товаров. Представляет
                      прдукцию более 750 производителей. Изделия из пластмасс,
                      садово-огородный инвентарь, посуда, электробытовые и
                      электроустановочные товары, зеркала, строительные материалы,
                      сантехника, метизы, замки. Фирменная сеть магазинов.
                  </p>
                  <span class="label label-info">Скидка составляет <?php echo $this->discounts['noht']; ?>%</span>
              </td>
          </tr>
          <tr>
              <td style="vertical-align: top">
                  <br>
                  <a href="http://www.alidi.ru/">
                      <img width="180" src="http://www.alidi.ru/bitrix/templates/alidi/img/logo.png">
                  </a>
              </td>
              <td style="padding-left: 10px">
                  <br>
                  <p>
                      АЛИДИ – ведущая Российская дистрибьюторская и логистическая 
                      компания, основанная в 1992 году в Нижнем Новгороде. 
                      Сегодня АЛИДИ имеет филиалы в 21 регионе России, включая 
                      Москву и Санкт-Петербург, а также в Республике Беларусь и в Кении.
                  </p>
                  <span class="label label-info">Скидка составляет <?php echo $this->discounts['alidi']; ?>%</span>
              </td>
          </tr>
          <tr>
              <td style="vertical-align: top">
                  <br>
                  <a href="http://www.ugdvor.nnov.ru/">
                      <img width="180" src="/img/logo_ugdvor.jpg">
                  </a>
              </td>
              <td style="padding-left: 10px">
                  <br>
                  <p>
                      “Южный Двор” - один из крупнейших дистрибьютеров отечественных 
                      и зарубежных производителей бытовой химии, парфюмерии, 
                      средств гигиены и товаров повседневного спроса.
                  </p>
                  <span class="label label-info">Скидка составляет <?php echo $this->discounts['ugdvor']; ?>%</span>
              </td>
          </tr>
          <tr>
              <td style="vertical-align: top">
                  <br>
                  <a href="http://order-nn.ru/">
                      <img width="180" src="http://order-nn.ru/images/logo.png">
                  </a>
              </td>
              <td style="padding-left: 10px">
                  <br>
                  <p>
                      Компания занимается оптово-розничной торговлей строительным инструментом и материалами.
                      Известность брэнда ОРДЕР‚ который является зарегистрированным 
                      товарным знаком‚ в Нижнем Новгороде составляет не менее 70% 
                      для всего населения города и 95% в профессиональном сегменте.
                      Основной ассортимент компании: лакокрасочная продукция‚ 
                      сухие смеси и инструмент.
                  </p>
                  <span class="label label-info">Скидка составляет <?php echo $this->discounts['order']; ?>%</span>
              </td>
          </tr>
          <tr>
              <td style="vertical-align: top">
                  <br>
                  <a href="https://www.metro-cc.ru/">
                      <img width="180" src="https://www.metro-cc.ru/-/media/Global/Components/Shared_-_Media/metro-logo.jpg">
                  </a>
              </td>
              <td style="padding-left: 10px">
                  <br>
                  <p>
                      Компания МЕТРО Кэш энд Керри в составе международного торгового холдинга МЕТРО ГРУП.
                      На сегодняшний день российское подразделение компании 
                      МЕТРО Кэш энд Керри открыло 68 торговых центра в 45 регионах страны. 
                      Продажи МЕТРО Кэш энд Керри, Россия за 2012 год составили 
                      4, 121 млрд. евро (рост по сравнению с предыдущим годом – более 20 %). 
                      Количество сотрудников превышает 19 200 человек.
                  </p>
                  <span class="label label-info">Скидка составляет <?php echo $this->discounts['metro']; ?>%</span>
              </td>
          </tr>
      </table>
      <br>
      <br>
    </div>
    
    <div class="col-sm-4 blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <?php echo $this->form; ?>
      </div>
    </div><!-- /.blog-sidebar -->
</div>
