<div class="row">
    <div class="col-sm-8 blog-main"> 
        <h2>Действующие акции</h2> 
        <p>Участникам кооператива нашими партнерами предоставляются акции</p>
        <table class="livetable">
            <tr>
                <td style="vertical-align: top">
                    <img width="130" src="/img/promo.png">
                </td>
                <td style="padding-left: 10px">
                    <p>
                        В марте месяце 2017г. сеть <b>АЗС «Терминал»</b>
                        проводит акцию по розыгрышу 20 л. топлива среди пайщиков кооператива
                        <b>ПК ВО «СОДЕЙСТВИЕ»</b>. В акции принимают участие пайщики, участвующие 
                        в программе «Выгодное топливо» и у которых есть не менее пяти 
                        привлеченных членов кооператива , которые так же являются 
                        участниками в данной программе.
                    </p>
                </td>
            </tr>
        </table>
    </div>
    
    <div class="col-sm-4 blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <?php echo $this->form; ?>
      </div>
    </div><!-- /.blog-sidebar -->
</div>
