<h2>Действующие акции</h2> 
<p>Участникам кооператива нашими партнерами предоставляются <a href="#bottom">акции*</a></p>

<?php 
if (count($this->promos)):
    $i = 0;
    foreach ($this->promos as $r):
    $i++;
    ?>
<?php if (($i-1)%3==0): ?><div class="row"><?php endif; ?>
    <div class="col-md-4">
        <div class="img-thumbnail promoimage">
            <a href="<?php echo $r['file']; ?>" target="blank" data-lightbox="roadtrip" data-title="<?php echo $r['name']; ?>">
                <img data-src="<?php echo $r['file']; ?>" width="100%">
            </a>
        </div>
        <p><?php echo $r['name']; ?></p>
    </div>
<?php if ($i%3==0): ?></div><?php endif; ?>

<?php endforeach; ?>
<?php if ($i%3!=0): ?></div><?php endif; ?>
<?php else: ?>
<div class="alert alert-info">
    <strong>Промо-акции отсутствуют</strong>
</div>
<?php endif; ?>

<script type='text/javascript'>
    [].forEach.call(document.querySelectorAll('img[data-src]'),    function(img) {
      img.setAttribute('src', img.getAttribute('data-src'));
      img.onload = function() {
        img.removeAttribute('data-src');
      };
    });
</script>

<div  class="col-md-12">
    <small><a name="bottom"></a>* - партнерами кооператива не гарантируется постоянное наличие акционных товаров в точках продаж</small>
</div>
