<div class="col-md-6">
    <h2>Личный кабинет</h2>        

    <p><?php echo $this->resources['fullname']; ?></p>
    <p>
        <?php echo $this->resources['email']; ?>
        <?php if($this->resources['email_confirmed_date'] === null): ?>
        <span class="label label-warning">Не подтвержден</span>
        <?php else: ?>
        <span class="label label-success">Подтвержден</span>
        <?php endif; ?>
    </p>
</div>


