<h3>Документы целевой Программы "Экономим вместе с МЕТРО"</h3>
<ul class="media-list">
    
    <li class="media">
        <a class="pull-left" href="/files/Metro.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Положение ЦП "Экономим вместе с МЕТРО"</h4>
            Настоящее   «Положение»   разработано   в   соответствии   с   Уставом   и   «Положением   об
            имуществе и фондах» ПК ВО "СОДЕЙСТВИЕ"
        </div>
    </li>
    
    <li class="media">
        <a class="pull-left" href="/files/MetroOferta.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Договор-оферта</h4>
            Договор-оферта с пайщиком ПК ВО "СОДЕЙСТВИЕ" на участие в целевой Программе «Экономим вместе с МЕТРО»
        </div>
    </li>
    
    <li class="media">
        <a class="pull-left" href="/files/MetroDog.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Договор об участии в целевой Программе</h4>
            Образец письменного договора об участии пайщика ПК ВО "СОДЕЙСТВИЕ" в целевой Программе "Экономим вместе с МЕТРО"
        </div>
    </li>
    
</ul>

<br>
<br>
<br>