<h3>Документы целевой Программы "Имущество на паях"</h3>
<ul class="media-list">
    
    <li class="media">
        <a class="pull-left" href="/files/Napayah.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Положение ЦП "Имущество на паях"</h4>
            Настоящее   «Положение»   разработано   в   соответствии   с   Уставом   и   «Положением   об
            имуществе и фондах» ПК ВО "СОДЕЙСТВИЕ"
        </div>
    </li>
    
</ul>

<br>
<br>
<br>