<h3>Документы целевой Программы "Стол заказов"</h3>
<ul class="media-list livedoc">
    
    <li class="media">
        <a class="pull-left" href="/files/StolZakazov.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Положение ЦП "Стол заказов"</h4>
            Настоящее   «Положение»   разработано   в   соответствии   с   Уставом   и   «Положением   об
            имуществе и фондах» ПК ВО "СОДЕЙСТВИЕ"
        </div>
    </li>
    
    <li class="media">
        <a class="pull-left" href="/files/StolZakazovOferta.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Договор-оферта</h4>
            Договор-оферта с пайщиком ПК ВО "СОДЕЙСТВИЕ" на участие в целевой Программе «Стол заказов»
        </div>
    </li>
    
    <li class="media">
        <a class="pull-left" href="/files/StolZakazovHozDog.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Договор об участии в хозяйственной деятельности</h4>
            Образец договора об участии в хозяйственной деятельности пайщика ПК ВО "СОДЕЙСТВИЕ"
            с учетом целевой Программы "Стол заказов"
        </div>
    </li>
    
    <li class="media">
        <a class="pull-left" href="/files/StolZakazovDog.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Договор об участии в целевой Программе</h4>
            Образец письменного договора об участии пайщика ПК ВО "СОДЕЙСТВИЕ" в целевой Программе "Стол заказов"
        </div>
    </li>
    
</ul>

<br>
<br>
<br>