<h3>Документы целевой Программы "Выгодное топливо"</h3>
<ul class="media-list">
    
    <li class="media">
        <a class="pull-left" href="/files/Toplivo.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Положение ЦП "Выгодное топливо"</h4>
            Настоящее   «Положение»   разработано   в   соответствии   с   Уставом   и   «Положением   об
            имуществе и фондах» ПК ВО "СОДЕЙСТВИЕ"
        </div>
    </li>
    
    <li class="media">
        <a class="pull-left" href="/files/ToplivoDog.pdf">
            <img class="media-object" src="/img/pdfdoc.png" alt="Просмотреть документ" width="64" height="64">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Договор об участии в целевой Программе</h4>
            Образец письменного договора об участии пайщика ПК ВО "СОДЕЙСТВИЕ" в целевой Программе "Выгодное топливо"
        </div>
    </li>
    
</ul>

<h3>Список АЗС партнеров</h3>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>Партнер</th>
            <th>Месторасположение АЗС</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС № 142 Н.Новгород ул. Циолковского 42
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                Автоматическая АЗС#1 на пересечении улиц Ванеева-Козицкого
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                Автоматическая АЗС#2 напротив ААЗС#1 (ул. Ванеева 205)
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС №109 г. Бор ул Республиканская 39
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                Автоматическая АЗС#3 развязка пр. Ленина и Комсомольского шоссе
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                Автоматическая АЗС#4 Анкудимиовсое шоссе напротив д.16
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС №104 трасса Н.Новгород-Киров около д.Садомово
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС №24 трасса Р125 п. Новинки Нижегородская обл.
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС №251 г.Богородск Нижегородское ш.1
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС №206 г. Н.Новгород пр-т Гагарина 127
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС № 21 Городецкий р-н д. Федурино
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС № 315 Н.Новгород ул. Усольская 30а 
            </td>
        </tr>
        <tr>
            <td>
                ООО «Терминал»
            </td>
            <td>
                АЗС №316 Н. Новгород Новополевая 36а
            </td>
        </tr>
    </tbody>    
</table>

<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
    ymaps.ready(init);
    var myMap, 
        myPlacemark;

    function init(){ 
        myMap = new ymaps.Map("map", {
            center: [56.31162277, 43.96415754],
            zoom: 8
        }, {
            searchControlProvider: 'yandex#search'
        }); 

        myMap.geoObjects.add(new ymaps.Placemark([56.33659379, 43.84802047], {
            hintContent: 'АЗС № 142 Н.Новгород ул. Циолковского 42'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.29037552, 44.03564904], {
            hintContent: 'Автоматическая АЗС#1 на пересечении улиц Ванеева-Козицкого'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.29027707, 44.03685603], {
            hintContent: 'Автоматическая АЗС#2 напротив ААЗС#1 (ул. Ванеева 205)'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.36988208, 44.08106957], {
            hintContent: 'АЗС №109 г. Бор ул Республиканская 39'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.29678321, 43.93540952], {
            hintContent: 'Автоматическая АЗС#3 развязка пр. Ленина и Комсомольского шоссе'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.27565582, 43.98933802], {
            hintContent: 'Автоматическая АЗС#4 Анкудимиовсое шоссе напротив д.16'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.76631344, 44.43943415], {
            hintContent: 'АЗС №104 трасса Н.Новгород-Киров около д.Садомово'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.20415478, 43.86422370], {
            hintContent: 'АЗС №24 трасса Р125 п. Новинки Нижегородская обл.'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.11692680, 43.53975151], {
            hintContent: 'АЗС №251 г.Богородск Нижегородское ш.1'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.22816670, 43.94195948], {
            hintContent: 'АЗС №206 г. Н.Новгород пр-т Гагарина 127'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.80465588, 43.38136707], {
            hintContent: 'АЗС № 21 Городецкий р-н д. Федурино'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.27949368, 43.89244590], {
            hintContent: 'АЗС № 315 Н.Новгород ул. Усольская 30а'
        }));
        
        myMap.geoObjects.add(new ymaps.Placemark([56.20747663, 43.77002988], {
            hintContent: 'АЗС №316 Н. Новгород Новополевая 36а'
        }));
    }
</script>
<div id="map" style="width: 100%; height: 500px; margin-bottom: 30px"></div>

<noscript style="color:#c00;font-size:16px;font-weight:bold;">
    Виджет карты использует JavaScript. Включите его в настройках вашего браузера.
</noscript>

<br>
<br>
<br>