<h1 class="page-header">Прайс-листы</h1>

<a href="<?php echo $this->url(array(), 'admin-pricelists-add'); ?>" class="btn btn-default">
    <span class="glyphicon glyphicon-plus"></span>
    Новый прайс-лист
</a>

<?php if (count($this->records)): ?>
<table class="table table-striped">
    <col width="50%">
    <col width="20%">
    <col width="15%">
    <col width="15%">
    <caption></caption>
    <thead>
        <tr>
            <th>Название</th>
            <th>Файл</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->records as $r): ?>

    <tr>        
        <td>
            <?php echo $r['name']; ?>
        </td>
        <td>            
            <a href="/pricelists/<?php echo $r['filename']; ?>" title="<?php echo $r['filename']; ?>">
                <span class="glyphicon glyphicon-paperclip"></span>
                <?php echo $r['filename']; ?>
            </a>  
        </td>
        <td>
            <a href="<?php echo $this->url(array('id' => $r['id']), 'admin-pricelists-edit'); ?>" class="btn btn-primary">
                <span class="glyphicon glyphicon-pencil"></span>
                Редактировать
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url(array('id' => $r['id']), 'admin-pricelists-del'); ?>" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
                Удалить
            </a>
        </td>
    </tr>

    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="alert alert-info">
    <strong>Нет прайс-листов</strong>
</div>
<?php endif; 

