<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Greben V">
    <link rel="shortcut icon" href="/img/favicon.ico">

    <title>Панель администратора</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    
    <style type="text/css">
        /* Sticky footer styles
        -------------------------------------------------- */
        html {
          position: relative;
          min-height: 100%;
        }
        body {
          /* Margin bottom by footer height */
          margin-bottom: 60px;
          background: url(/img/bacground.png);
        }
        #footer {
          position: absolute;
          bottom: 0;
          width: 100%;
          /* Set the fixed height of the footer here */
          height: 60px;
          background-color: #f5f5f5;
        }


        /* Custom page CSS
        -------------------------------------------------- */
        /* Not required for template or sticky footer method. */

        .container {
          width: auto;
          max-width: 970px;
          padding: 0 15px;
        }
        .container .text-muted {
          margin: 20px 0;
        }
    </style>
  </head>

  <body>

    <div class="container">
        <div class="col-md-4"></div>
        
        <div class="col-md-4">
            <h2>Авторизация</h2>        

            <?php echo $this->form; ?>

            <a href="<?php echo $this->url(array(), 'home'); ?>">
                ← На главную
            </a>
        </div>
        
        <div class="col-md-4"></div>

    </div> <!-- /container -->
    
    <div id="footer">
      <div class="container">
        &copy; ПК ВО Содействие 2017
        <br>
        <small>Все права защищены.</small>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

