<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Greben V">
    <link rel="shortcut icon" href="/img/favicon.ico">

    <title>Панель администратора</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>

    <div class="container">
        <div class="col-md-4"></div>
        
        <div class="col-md-4">
            <h2>Авторизация</h2>        

            <?php echo $this->form; ?>

            <a href="<?php echo $this->url(array(), 'home'); ?>">
                ← На главную
            </a>
        </div>
        
        <div class="col-md-4"></div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

