<div class="row placeholders">
    <div class="col-xs-6 col-sm-4 placeholder">
        <a href="/files/BlankForUr.docx" download title="Скачать бланк заявления от юридического лица">
            <img src="/img/docico.png" class="img-thumbnail" width="150" height="200" alt="Скачать бланк заявления">
        </a>
        <h4>Юр. лицо</h4>
        <span class="text-muted">Бланк заявления от юридического лица</span>
    </div>
    <div class="col-xs-6 col-sm-4 placeholder">
        <a href="/files/BlankForIP.docx" download title="Скачать бланк заявления от ИП">
            <img src="/img/docico.png" class="img-thumbnail" width="150" height="200" alt="Скачать бланк заявления">
        </a>
        <h4>ИП</h4>
        <span class="text-muted">Бланк заявления от индивидуального предпринимателя</span>
    </div>
    <div class="col-xs-6 col-sm-4 placeholder">
        <a href="/files/BlankForFiz.docx" download title="Скачать бланк заявления от физического лица">
            <img src="/img/docico.png" class="img-thumbnail" width="150" height="200" alt="Скачать бланк заявления">
        </a>
        <h4>Физ. лицо</h4>
        <span class="text-muted">Бланк заявления от физического лица</span>
    </div>
</div>

<?php 
    //var_dump($this->firstinput);
    echo $this->form; 