<div class="jumbotron">
    <!--<div class="container">-->
        <h3>Заявка отправлена</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Pellentesque in euismod nisl, a faucibus turpis. 
            Phasellus euismod commodo arcu, luctus elementum dolor gravida a. 
            Aenean sit amet tortor tortor. Suspendisse sollicitudin ac lorem in aliquam. 
            Etiam nisl nisl, hendrerit sed quam non, faucibus ullamcorper justo. 
            Morbi quis libero dolor. Donec scelerisque rhoncus justo, a ultricies quam euismod vel. 
            Suspendisse dictum turpis sed eros molestie, id gravida ipsum porttitor. 
            Fusce sollicitudin, magna venenatis posuere accumsan, velit metus fermentum turpis, eget blandit risus libero aliquet tellus. 
            Duis sit amet ante vitae justo sagittis ornare non vitae sapien. 
            Ut in convallis neque, eget rhoncus ex. Suspendisse convallis non nisl posuere commodo. 
            Quisque varius eleifend consectetur. Duis in sagittis nisl.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" role="button" href="<?php echo $this->url(array(), 'home'); ?>">На главную</a>
        </p>
    <!--</div>-->
</div>

