<?php if (count($this->records)): ?>
<table class="table table-striped">
    <col width="20%">
    <col width="70%">
    <col width="10%">
    <caption></caption>
    <thead>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->records as $r): ?>

    <tr>        
        <td>
            <?php echo $r['name']; ?>
        </td>
        <td>
            <?php echo $r['note']; ?>
        </td>
        <td>
            <div class="dropdown">
                <a class="btn btn-link dropdown-toggle pull-left" data-toggle="dropdown" href="#">
                    Еще
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li><a tabindex="-1" href="<?php echo $this->url(array('id' => $r['id']), 'admin-resources-edit'); ?>">Редактировать</a></li>
                    <li class="divider"></li>
                    <li><a tabindex="-1" href="<?php echo $this->url(array('id' => $r['id']), 'admin-resources-del'); ?>">Удалить</a></li>
                </ul>
            </div>
        </td>
    </tr>

    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="alert alert-info">
    <strong>Нет программ</strong>
</div>
<?php endif; ?>

