<?php if ($this->pageCount): ?>
<ul class="pagination">
    <?php if (!isset($this->previous)): ?>
    <li class="disabled"><a href="#">&#60;&#60;</a></li>
    <li class="disabled"><a href="#">&#60;</a></li>    
    <?php else: ?>
    <li>
        <a href="<?php echo $this->url(array('page' => $this->first));?>">&#60;&#60;</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('page' => $this->previous));?>">&#60;</a>
    </li>
    <?php endif; ?>
  <?php foreach ($this->pagesInRange as $page): ?>
  <li class="<?php echo ($page == $this->current) ? 'active' : ''; ?>">
      <a href="<?php echo $this->url(array('page' => $page));?>">
          <?php echo $page; ?>
      </a>
  </li>
  <?php endforeach; ?>
  <?php if (!isset($this->next)): ?>
    <li class="disabled"><a href="#">&#62;</a></li>
    <li class="disabled"><a href="#">&#62;&#62;</a></li>
  <?php else: ?>
  <li>
      <a href="<?php echo $this->url(array('page' => $this->next));?>">&#62;</a>
  </li>
  <li>
      <a href="<?php echo $this->url(array('page' => $this->last));?>">&#62;&#62;</a>
  </li>
  <?php endif; ?>
</ul>
<?php endif; ?>
