<div class="col-md-12">
    <ol class="breadcrumb">
        <?php echo $this->crumps;?>
    </ol>
</div>

<div class="col-sm-3 hidden-xs hidden-sm">
    <div id="good_tree" onshow="loadmenu()">Каталог товаров</div>
</div>

<div class="col-md-9">
    <?php if (isset($this->folder)):?>
    <h2><?php echo $this->folder["name"];?></h2>
    <?php else: ?>
    <h2>Стол заказов</h2>
    <?php endif; ?>

    <?php if (count($this->goods)):?>
    <div class="catalog_block">
        <ul class="catalog_list clearfix">
            <?php foreach ($this->goods as $r): ?>
            <li class="cat_l_item">
                <?php if (!$r['folder']||empty($r['folder'])):?>
                <a href="/catalog/item/<?php echo $r['id']; ?>">
                <?php else:?>
                <a href="/catalog/folder/<?php echo $r['id']; ?>">
                <?php endif;?>
                    <div class="cat_l_i_wrap">
                        <div class="cat_l_item_img">
                            <?php if (!$r['folder']||empty($r['folder'])):?>
                            <img src="<?php echo $this->imagehost . $r['id']; ?>" alt="<?php echo $r['name']; ?>" title="<?php echo $r['name']; ?>">
                            <?php else:?>
                            <img src="<?php echo empty($r['filename'])? '/img/folder.png' : $this->imagehost . $r['id']; ?>" alt="<?php echo $r['name']; ?>" title="<?php echo $r['name']; ?>">
                            <?php endif;?>
                        </div>
                        <div class="cat_l_item_slider">&nbsp;</div>
                        <div class="cat_l_item_hline"><?php echo $r['name']; ?></div>
                        <?php if (!$r['folder']||empty($r['folder'])):?>
                        <small><?php  echo $r['exist'] ? 'В наличии' : 'Под заказ';?></small>
                        <div class="cat_l_item_wp_price">
                            <span class="cat_l_item_price"><?php echo $r['price']; ?></span> р.
                        </div>
                        <?php endif; ?>
                    </div>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php else: ?>
    <div class="alert alert-info">
        <strong>Папка пуста</strong>
    </div>
    <?php endif; ?>
</div>

<div class="col-md-12">
    <ol class="breadcrumb">
        <?php echo $this->crumps;?>
    </ol>
</div>
