<h2>Каталог товаров</h2>
<p>Далее представлены товары</p>

<?php 
if (count($this->goods)):
    $i = 0;
    foreach ($this->goods as $r):
    $i++;
?>
<ul>
<?php if (($i-1)%3==0): ?><div class="row"><?php endif; ?>
    <li class="inner_sections">
        <div class="img-thumbnail promoimage">
            
        </div>
        <p><?php echo $r['name']; ?></p>
    </div>
<?php if ($i%3==0): ?></div><?php endif; ?>
</ul>

<?php endforeach; ?>
<?php if ($i%3!=0): ?></div><?php endif; ?>
<?php else: ?>
<div class="alert alert-info">
    <strong>Товары отсутствуют</strong>
</div>
<?php endif; ?>

<script type='text/javascript'>
//    [].forEach.call(document.querySelectorAll('img[data-src]'), function(img) {
//      img.setAttribute('src', img.getAttribute('data-src'));
//      img.onload = function() {
//        img.removeAttribute('data-src');
//      };
//    });
</script>
