<div class="col-md-10">
    <form role="form" method="GET" action="<?php echo $this->url(array('page' => 1), 'catalog-search'); ?>">
        <div class="input-group">
            <input type="test" name="query" class="form-control" placeholder="Поиск">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-warning">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
        </div>
    </form>
</div>
<div class="col-md-2"><div id="basket_widget"></div></div>

<div class="col-md-12">
    <ol class="breadcrumb">
        <?php echo $this->crumps;?>
    </ol>
</div>

<div class="col-sm-3 hidden-xs hidden-sm">
    <div id="good_tree" onshow="loadmenu()"></div>
</div>

<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->item['name']; ?></h3>
        </div>
        <div class="panel-body">
            <div class="cat_item_img_full">
                <img src="<?php echo $this->imagehost.$this->item['id']; ?>">
            </div>
            <div class="cat_item_basket">
                <?php if (Zend_Auth::getInstance()->hasIdentity()):?>
                <button type="button" class="btn btn-default" onclick="addToBasket(<?php echo $this->item['id']; ?>)">
                    <span class="glyphicon glyphicon-shopping-cart"></span> В корзину
                </button>
                <?php else:?>
                <button type="button" class="btn btn-default" disabled="disabled" data-toggle="tooltip" data-placement="top" title="Для этого действия требуется авторизоваться">
                    <span class="glyphicon glyphicon-shopping-cart"></span> В корзину
                </button>
                <?php endif; ?>
            </div>
            
            <ul class="nav nav-tabs">
                <li class="active"><a href="#">Описание товара</a></li>
            </ul>

            <dl class="dl-horizontal">
                <dt>Код товара</dt>
                <dd><?php echo $this->item['id']; ?></dd>

                <dt>Описание</dt>
                <dd><?php echo $this->item['description']; ?></dd>

                <dt>Артикул</dt>
                <dd><?php echo $this->item['article']; ?></dd>

                <dt>Цена</dt>
                <dd><span><?php echo $this->item['price'];?></span> р.</dd>

                <dt>Наличие</dt>
                <dd><small><?php echo $this->item['instock']?'в наличии':'под заказ';?></small></dd>
            </dl>
            
            <h4>Пункт выдачи товаров</h4>
            <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
            <script type="text/javascript">
                ymaps.ready(init);
                var myMap, 
                    myPlacemark;

                function init(){ 
                    myMap = new ymaps.Map("map", {
                        center: [56.28972796, 43.98710038],
                        zoom: 17
                    }, {
                        searchControlProvider: 'yandex#search'
                    }); 

                    myPlacemark = new ymaps.Placemark([56.28972796, 43.98710038], {
                        hintContent: 'Пункт выдачи товара', 
                        balloonContent: 'ПК ВО Содействие' 
                    });

                    myMap.geoObjects.add(myPlacemark);
                }
            </script>

            <div id="map" style="width: 100%; height: 500px; margin-bottom: 30px"></div>

            <noscript style="color:#c00;font-size:16px;font-weight:bold;">
                Виджет карты использует JavaScript. Включите его в настройках вашего браузера.
            </noscript>
        </div>
    </div>
</div>
