<?php if (Zend_Auth::getInstance()->hasIdentity()):?>
<div class="col-md-10">
    <ol class="breadcrumb">
        <?php echo $this->crumps;?>
    </ol>    
</div>
<div class="col-md-2"><div id="basket_widget"></div></div>
<?php else: ?>
<div class="col-md-12">
    <ol class="breadcrumb">
        <?php echo $this->crumps;?>
    </ol>    
</div>
<?php endif; ?>

<div class="col-sm-3 hidden-xs hidden-sm">
    <div id="good_tree" onshow="loadmenu()">Каталог товаров</div>
</div>

<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->item['name']; ?></h3>
        </div>
        <div class="panel-body">
            <div class="cat_l_item_img">
                <img src="<?php echo $this->imagehost . $this->item['id']; ?>" alt="<?php echo $this->item['name']; ?>" title="<?php echo $this->item['name']; ?>">
            </div>

            <dl class="dl-horizontal">
                <dt>Код товара</dt>
                <dd><?php echo $this->item['id']; ?></dd>

                <dt>Описание</dt>
                <dd><?php echo $this->item['description']; ?></dd>

                <dt>Артикул</dt>
                <dd><?php echo $this->item['article']; ?></dd>

                <dt>Цена</dt>
                <dd><span><?php echo $this->item['price']; ?></span> р.</dd>

                <dt>Наличие</dt>
                <dd><small><?php  echo $this->item['instock'] ? 'в наличии' : 'под заказ';?></small></dd>
            </dl>
            <?php if (Zend_Auth::getInstance()->hasIdentity()):?>
            <button type="button" class="btn btn-success" onclick="addToBasket(<?php echo $this->item['id']; ?>)">
                <span class="glyphicon glyphicon-shopping-cart"></span> В корзину
            </button>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="col-md-12">
    <ol class="breadcrumb">
        <?php echo $this->crumps;?>
    </ol>
</div>
