<style type="text/css">@import "/css/tree.css";</style>
<style type="text/css">@import "/css/tree_1.css";</style>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/tree.js"></script>
<!--<script type="text/javascript" src="/js/tree_1.js"></script>-->

<ul class="Container" id="tree">
  <?php foreach ($this->folders as $f): ?>
  <li id="<?php echo $f['id']; ?>" class="Node IsRoot IsLast ExpandClosed">
    <div class="Expand" onclick="clickExpand()"></div>
    <div class="Content"><a href="/catalog/folder/<?php echo $f['id']; ?>"><?php echo $f['name']; ?></a></div>
    <ul class="Container"></ul>
  </li>
  <?php endforeach; ?>
</ul>

<header>
    <div class="cd-dropdown-wrapper">
        <a class="cd-dropdown-trigger" href="#0">Dropdown</a>
      <nav class="cd-dropdown">
        <h2>Title</h2>
        <a href="#0" class="cd-close">Close</a>
        <ul class="cd-dropdown-content">
          <li class="has-children">
            <a href="https://codyhouse.co/?p=748">Clothing</a>

            <ul class="cd-secondary-dropdown is-hidden">
              <li class="go-back"><a href="#0">Menu</a></li>
              <li class="see-all"><a href="https://codyhouse.co/?p=748">All Clothing</a></li>
              <li class="has-children">
                <a href="https://codyhouse.co/?p=748">Accessories</a>

                <ul class="is-hidden">
                  <li class="go-back"><a href="#0">Clothing</a></li>
                  <li class="see-all"><a href="https://codyhouse.co/?p=748">All Accessories</a></li>
                  <li class="has-children">
                    <a href="#0">Beanies</a>

                    <ul class="is-hidden">
                      <li class="go-back"><a href="#0">Accessories</a></li>
                      <li class="see-all"><a href="https://codyhouse.co/?p=748">All Benies</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Caps &amp; Hats</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Gifts</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Scarves &amp; Snoods</a></li>
                    </ul>
                  </li>
                  <li class="has-children">
                    <a href="#0">Caps &amp; Hats</a>

                    <ul class="is-hidden">
                      <li class="go-back"><a href="#0">Accessories</a></li>
                      <li class="see-all"><a href="https://codyhouse.co/?p=748">All Caps &amp; Hats</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Beanies</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Caps</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Hats</a></li>
                    </ul>
                  </li>
                  <li><a href="https://codyhouse.co/?p=748">Glasses</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Gloves</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Jewellery</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Scarves</a></li>
                </ul>
              </li>

              <li class="has-children">
                <a href="https://codyhouse.co/?p=748">Bottoms</a>

                <ul class="is-hidden">
                  <li class="go-back"><a href="#0">Clothing</a></li>
                  <li class="see-all"><a href="https://codyhouse.co/?p=748">All Bottoms</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Casual Trousers</a></li>
                  <li class="has-children">
                    <a href="#0">Jeans</a>

                    <ul class="is-hidden">
                      <li class="go-back"><a href="#0">Bottoms</a></li>
                      <li class="see-all"><a href="https://codyhouse.co/?p=748">All Jeans</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Ripped</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Skinny</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Slim</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Straight</a></li>
                    </ul>
                  </li>
                  <li><a href="#0">Leggings</a></li>
                  <li><a href="#0">Shorts</a></li>
                </ul>
              </li>

              <li class="has-children">
                <a href="https://codyhouse.co/?p=748">Jackets</a>

                <ul class="is-hidden">
                  <li class="go-back"><a href="#0">Clothing</a></li>
                  <li class="see-all"><a href="https://codyhouse.co/?p=748">All Jackets</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Blazers</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Bomber jackets</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Denim Jackets</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Duffle Coats</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Leather Jackets</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Parkas</a></li>
                </ul>
              </li>

              <li class="has-children">
                <a href="https://codyhouse.co/?p=748">Tops</a>

                <ul class="is-hidden">
                  <li class="go-back"><a href="#0">Clothing</a></li>
                  <li class="see-all"><a href="https://codyhouse.co/?p=748">All Tops</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Cardigans</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Coats</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Polo Shirts</a></li>
                  <li><a href="https://codyhouse.co/?p=748">Shirts</a></li>
                  <li class="has-children">
                    <a href="#0">T-Shirts</a>

                    <ul class="is-hidden">
                      <li class="go-back"><a href="#0">Tops</a></li>
                      <li class="see-all"><a href="https://codyhouse.co/?p=748">All T-shirts</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Plain</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Print</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Striped</a></li>
                      <li><a href="https://codyhouse.co/?p=748">Long sleeved</a></li>
                    </ul>
                  </li>
                  <li><a href="https://codyhouse.co/?p=748">Vests</a></li>
                </ul>
              </li>
            </ul>
             .cd-secondary-dropdown 
          </li>
           .has-children 

          <li class="has-children">
            <a href="https://codyhouse.co/?p=748">Gallery</a>

            <ul class="cd-dropdown-gallery is-hidden">
              <li class="go-back"><a href="#0">Menu</a></li>
              <li class="see-all"><a href="https://codyhouse.co/?p=748">Browse Gallery</a></li>
              <li>
                <a class="cd-dropdown-item" href="https://codyhouse.co/?p=748">
                  <img src="img/img.png" alt="Product Image">
                  <h3>Product #1</h3>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item" href="https://codyhouse.co/?p=748">
                  <img src="img/img.png" alt="Product Image">
                  <h3>Product #2</h3>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item" href="https://codyhouse.co/?p=748">
                  <img src="img/img.png" alt="Product Image">
                  <h3>Product #3</h3>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item" href="https://codyhouse.co/?p=748">
                  <img src="img/img.png" alt="Product Image">
                  <h3>Product #4</h3>
                </a>
              </li>
            </ul>
             .cd-dropdown-gallery 
          </li>
           .has-children 

          <li class="has-children">
            <a href="https://codyhouse.co/?p=748">Services</a>
            <ul class="cd-dropdown-icons is-hidden">
              <li class="go-back"><a href="#0">Menu</a></li>
              <li class="see-all"><a href="https://codyhouse.co/?p=748">Browse Services</a></li>
              <li>
                <a class="cd-dropdown-item item-1" href="https://codyhouse.co/?p=748">
                  <h3>Service #1</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-2" href="https://codyhouse.co/?p=748">
                  <h3>Service #2</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-3" href="https://codyhouse.co/?p=748">
                  <h3>Service #3</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-4" href="https://codyhouse.co/?p=748">
                  <h3>Service #4</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-5" href="https://codyhouse.co/?p=748">
                  <h3>Service #5</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-6" href="https://codyhouse.co/?p=748">
                  <h3>Service #6</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-7" href="https://codyhouse.co/?p=748">
                  <h3>Service #7</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-8" href="https://codyhouse.co/?p=748">
                  <h3>Service #8</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-9" href="https://codyhouse.co/?p=748">
                  <h3>Service #9</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-10" href="https://codyhouse.co/?p=748">
                  <h3>Service #10</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-11" href="https://codyhouse.co/?p=748">
                  <h3>Service #11</h3>
                  <p>This is the item description</p>
                </a>
              </li>

              <li>
                <a class="cd-dropdown-item item-12" href="https://codyhouse.co/?p=748">
                  <h3>Service #12</h3>
                  <p>This is the item description</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </header>
