<style type="text/css">@import "/css/tree.css";</style>
<!--<style type="text/css">@import "/css/tree_1.css";</style>-->
<!--<script type="text/javascript" src="/js/jquery.js"></script>-->
<!--<script type="text/javascript" src="/js/tree.js"></script>-->
<!--<script type="text/javascript" src="/js/tree_1.js"></script>-->

<div class="catalog_sidebar">
    <ul class="Container" id="tree">
      <?php foreach ($this->folders as $f): ?>
      <li data-submenu-id="submenu-<?php echo $f['id']; ?>" id="<?php echo $f['id']; ?>" class="catalog_sidebar_node Node IsRoot ExpandClosed">
        <div class="Expand" onclick="clickExpand()"></div>
        <a href="/catalog/folder/<?php echo $f['id']; ?>">
            <?php echo $f['name']; ?>
        </a>
        <ul class="Container"></ul>
        <div id="submenu-<?php echo $f['id']; ?>"  class="popover">
            <h3 class="popover-title"><?php echo $f['name']; ?></h3>
            <div class="popover-content"><img src="<?php echo $this->imagehost . $f['id']; ?>"></div>
        </div>
      </li>
      <?php endforeach; ?>
    </ul>
</div>
