<div class="col-md-10">
    <form role="form" method="GET" action="<?php echo $this->url(array('page' => 1), 'catalog-search'); ?>">
        <div class="input-group">
            <input type="test" name="query" class="form-control" placeholder="Поиск" value="<?php echo $this->escape($this->query); ?>">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-warning">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
        </div>
    </form>
</div>
<div class="col-md-2"><div id="basket_widget"></div></div>

<div class="col-md-12">
    <ol class="breadcrumb">
        <li><a href="/catalog/folder/0"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">Поиск</li>
    </ol>    
</div>

<div class="col-sm-3 hidden-xs hidden-sm">
    <div id="good_tree" onshow="loadmenu()"></div>
</div>

<div class="col-md-9">
    <?php if (count($this->paginator)): ?>
    <h2>Результаты поиска</h2>
    <div class="catalog_block">
        <ul class="catalog_list clearfix">
            <?php foreach ($this->paginator as $r): ?>
            <li class="cat_l_item">                
                <div class="cat_l_i_wrap">   
                    <a href="/catalog/item/<?php echo $this->escape($r->RecordID); ?>">
                        <small class="cat_l_item_id">Код <?php  echo $this->escape($r->RecordID);?></small>
                        <small class="cat_l_item_instock <?php  echo $this->escape($r->instock)?'instock_yes':'';?>">
                            <?php echo $this->escape($r->instock)?'в наличии':'под заказ';?>
                        </small>
                        <div class="cat_l_item_img">
                            <img data-src="<?php echo $this->imagehost.$this->escape($r->RecordID);?>">
                        </div>
                        <div class="cat_l_item_slider">&nbsp;</div>
                        <div class="cat_l_item_hline"><?php echo $this->queryobj->htmlFragmentHighlightMatches($this->escape($r->name)); ?></div>                      
                        <div class="cat_l_item_wp_price">
                            <span class="cat_l_item_price"><?php echo $this->escape($r->price); ?></span> &#8381;
                        </div>
                    </a>
                    <div class="cat_l_item_basket">
                        <?php if (Zend_Auth::getInstance()->hasIdentity()):?>
                        <button type="button" class="btn btn-default btn-xs" onclick="addToBasket(<?php echo $this->escape($r->RecordID); ?>)">
                            <span class="glyphicon glyphicon-shopping-cart"></span> В корзину
                        </button>
                        <?php else:?>
                        <button type="button" class="btn btn-default btn-xs" disabled="disabled" data-toggle="tooltip" data-placement="top" title="Для этого действия требуется авторизоваться">
                            <span class="glyphicon glyphicon-shopping-cart"></span> В корзину
                        </button>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php else: ?>
    <div class="alert alert-warning">
        <strong>По запросу "<?php echo $this->escape($this->query); ?>" ничего не найдено</strong>
    </div>
    <?php endif; ?>
</div>

<script type='text/javascript'>
    [].forEach.call(document.querySelectorAll('img[data-src]'), function(img) {
      img.setAttribute('src', img.getAttribute('data-src'));
      img.setAttribute('style', "background: none");
      img.onload = function() {
        img.removeAttribute('data-src');
      };
    });
</script>

<?php if (count($this->paginator)): ?>
<div class="col-md-12">
    <div class="text-center">
        <?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination_control.phtml', array('query' => $this->query)); ?>
    </div>    
</div>
<?php endif; ?>
