<a href="<?php echo $this->url(array(), 'admin-programs-add'); ?>" class="btn btn-default">
    <span class="glyphicon glyphicon-plus"></span>
    Новая целевая программа
</a>

<?php if (count($this->records)): ?>
<table class="table table-striped">
    <col width="20%">
    <col width="30%">
    <col width="20%">
    <col width="15%">
    <col width="15%">
    <caption></caption>
    <thead>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Страница</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->records as $r): ?>

    <tr>        
        <td>
            <?php echo $r['name']; ?>
        </td>
        <td>
            <?php echo $r['note']; ?>
        </td>
        <td>
            <?php echo $r['page']; ?>
        </td>
        <td>
            <a href="<?php echo $this->url(array('id' => $r['id']), 'admin-programs-edit'); ?>" class="btn btn-primary">
                <span class="glyphicon glyphicon-pencil"></span>
                Редактировать
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url(array('id' => $r['id']), 'admin-programs-del'); ?>" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
                Удалить
            </a>
        </td>
    </tr>

    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="alert alert-info">
    <strong>Нет программ</strong>
</div>
<?php endif; ?>

