<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type"	content="text/html" charset="utf-8"/>
        <base href="/"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="НПК Содействие">
        <meta name="author" content="Greben V">
        <link rel="shortcut icon" href="/img/favicon.ico">
    
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.css"/>
        <script src="/js/bootstrap.js"></script>
        
        <title>Содействие</title>
        
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="<?php echo $this->url(array(), 'admin'); ?>">
                  ПК ВО Содействие
              </a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->url(array(), 'admin'); ?>">Заявки</a></li>
                    <li><a href="<?php echo $this->url(array(), 'admin-resources'); ?>">Программы</a></li>
                    <li><a href="<?php echo $this->url(array(), 'admin-logout'); ?>">Выйти</a></li>
              </ul>
            </div>
          </div>
        </div>
        
        <div class="container-fluid">
            <div class="row-fluid">
                <!--Body content-->
                <br>
                <br>
                <br>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>