<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type"	content="text/html" charset="utf-8"/>
        <base href="/"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="НПК Содействие">
        <meta name="author" content="Greben V">
        <link rel="shortcut icon" href="/img/favicon.ico">
    
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.css"/>
        <script src="/js/bootstrap.js"></script>
        
        <title>Содействие</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="page-header">
                <h1>ADMINKA <small>Панель администрирования</small></h1>                
                <p class="text-right">
                    <a href="<?php echo $this->url(array(), 'home'); ?>">
                        На главную
                    </a>
                </p>
            </div>
            <div class="row-fluid">
                <!--Body content-->
                <?php
                    echo $this->layout()->content;
                ?>
            </div>
        </div>
    </body>
</html>