<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type"	content="text/html" charset="utf-8"/>
        <base href="/"/>
        <link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.css"/>
        <script src="/bootstrap/js/bootstrap.js"></script>
        
        <title>Кооператив</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="page-header">
                <h1>Потребительский кооператив</h1>
            </div>
            <div class="row-fluid">  
                <?php 
                    echo $this->layout()->content;
                ?>
            </div>
        </div>
    </body>
</html>