<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type"	content="text/html" charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="НПК Содействие">
        <meta name="author" content="Greben V">
        <meta name="yandex-verification" content="d3a3aded422cf85d" />
        <link rel="shortcut icon" href="/img/favicon.ico">

        <title>Содействие</title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/css/styles.css" rel="stylesheet">

        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        
        <!-- Lightbox -->
        <link href="/lightbox/css/lightbox.css" rel="stylesheet">
        <script type="text/javascript" src="/lightbox/js/lightbox.js"></script>
        <script>
            lightbox.option({
              'albumLabel': 'Изображение %1 из %2'
            })
        </script>
        
        <script type="text/javascript" src="/js/back-top.js"></script>
    </head>

    <body>
        
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function () {
                    try {
                        w.yaCounter42754339 = new Ya.Metrika({
                            id: 42754339,
                            clickmap: true,
                            trackLinks: true,
                            accurateTrackBounce: true
                        });
                    } catch (e) {
                    }
                });

                var n = d.getElementsByTagName("script")[0],
                        s = d.createElement("script"),
                        f = function () {
                            n.parentNode.insertBefore(s, n);
                        };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else {
                    f();
                }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/42754339" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
        
        <!-- BEGIN JIVOSITE CODE -->
        <script type='text/javascript'>
            (function () {
                var widget_id = 'uDzudLQqlo';
                var d = document;
                var w = window;
                function l() {
                    var s = document.createElement('script');
                    s.type = 'text/javascript';
                    s.async = true;
                    s.src = '//code.jivosite.com/script/widget/' + widget_id;
                    var ss = document.getElementsByTagName('script')[0];
                    ss.parentNode.insertBefore(s, ss);
                }
                if (d.readyState === 'complete') {
                    l();
                } else {
                    if (w.attachEvent) {
                        w.attachEvent('onload', l);
                    } else {
                        w.addEventListener('load', l, false);
                    }
                }
            })();
        </script>
        <!-- END JIVOSITE CODE -->
        
        <div class="container">            
            <div class="header">
                <?php
                echo $this->navigation()
                        ->menu()
                        ->renderMenu(null, array('ulClass' => 'nav nav-pills pull-right'));
                ?>
                <!--<img class="media-object" src="/img/logo.png" height="64">-->
                <h3 class="text-muted">ПК ВО Содействие</h3>
            </div>

            <?php echo $this->layout()->content; ?>         
        </div> <!-- /container -->
        
        <footer class="footer">
            <div class="col-sm-7">
                &copy; ПК ВО Содействие 2017
                <br>
                <small>Все права защищены.</small>
            </div>
            <div class="col-sm-2">
                <a href="https://smsc.ru" target="_blank"><img src="https://smsc.ru/im/smsc_button3.gif" alt="SMS-центр" border="0" height="31"></a>
            </div>
            <div class="col-sm-3">
                Дизайн и разработка сайта — 
                <br>
                <a href="http://regionsoft.ru/"><small>RegionSoft Developer Studio</small></a>
            </div>
        </footer> 
        
        <a href="#" id="toTop">
            <img alt="" src="/img/up.png">
        </a>
    </body>

<!-- >>>>> Developer Greben Viсtor -> https://github.com/Greben86 <<<<< -->
</html>